apiVersion: apps/v1
kind: Deployment
metadata:
  name: lugx-frontend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lugx-frontend
  template:
    metadata:
      labels:
        app: lugx-frontend
    spec:
      containers:
      - name: lugx-frontend
        image: salithaperera199914/frontend-app:v2
        ports:
        - containerPort: 3000
